MODEL:
  NAME: "deeplabv2_resnet101"  # deeplab_resnet101 & deeplabv3plus_resnet101
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  NUM_CLASSES: 19
DATASETS:
  SOURCE_TRAIN: "gtav_train"   # gtav_train and synthia_train
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  BASE_LR: 2.5e-5
  MAX_ITER: 62500
  STOP_ITER: 40000
  BATCH_SIZE: 2
  BETA: 1.0
  LAMBDA: 0.05


ACTIVE:
  NAME: 'DUC'
  RATIO: 0.01  #  0.01 for 5%
  KAPPA: 10
  SELECT_ITER: [10000, 12000, 14000, 16000, 18000]

OUTPUT_DIR: './output/deeplabv2/gtav'
LOG_NAME: 'log.txt'