OUTPUT_DIR: 'results/'

INPUT:
  SIZE: (256, 256)
  CROP_SIZE: (224, 224)
  SOURCE_TRANSFORMS: ('random_flip', 'random_resized_crop', 'normalize', 'colorjitter')
  TARGET_TRANSFORMS: ('random_flip', 'random_resized_crop', 'normalize')
  TEST_TRANSFORMS: ('center_crop', 'normalize')
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATASET:
  ROOT: 'data/list/'
  NAME: 'home'
  SOURCE_DOMAINS: ['Art', 'Clipart', 'Product', 'RealWorld']
  TARGET_DOMAINS: ['Art', 'Clipart', 'Product', 'RealWorld']
  NUM_CLASS: 65

DATALOADER:
  SOURCE:
    BATCH_SIZE: 32
  TARGET:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 32

TRAIN:
  PRINT_FREQ: 50
OPTIM:
  NAME: 'SGD'
  LR: 0.004

TRAINER:
  NAME: 'DUC'
  MAX_EPOCHS: 50
  BETA: 1.0
  LAMBDA: 0.05

SEED: 0
GPU_ID: 0
